name: oriel
favicon: null
layout_spectrum: 0.22453299816697836
typography_spectrum: 0.15669671772047877
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.22763711167499423
  lightness: 0.22310996358282864
  saturation: 0.5331830270588398
  rhythmicContrast: 0.16348441783338785
purpose: []
